project:
  type: website
  output-dir: docs
  resources:
    - "apple-touch-icon-precomposed.png"
    - "apple-touch-icon.png"
  render:
    - "index.qmd"
    - "data-cleaning.qmd"
    - "selection.qmd"
    - "associations.qmd"
    - "404.qmd"
format:
  html:
    theme:
      light: [default]
      dark: [darkly]
    css: theme.css
    code-fold: true
    code-link: true
    toc: true
    code-tools:
      source: repo
    html-math-method: katex
    self-contained: false
    self-contained-math: false
    mainfont: "Mulish"
    monofont: "Noto Sans Mono"
    doi: "10.1101/2022.08.16.22278320"

website:
  title: "Analysis by Constantine-Cooke et al."
  favicon: "favicon.png"
  twitter-card:
    creator: "@nathansam"
    site: "@EdinUni_IGC"
  open-graph: true
  navbar:
    background: "#004276"
    search: true
    right:
      - href: index.qmd
        text: About
      - data-cleaning.qmd
      - selection.qmd
      - associations.qmd
      - icon: github
        href: https://github.com/vallejosgroup/lcmm-site
      - icon: person-rolodex
        href: https://vallejosgroup.github.io
  page-footer:
    background: "#004276"
    left: "Copyright 2023, The Authors"
    right:
      - icon: github
        href: https://github.com/vallejosgroup/lcmm-site
      - icon: twitter
        href: https://twitter.com/IBDNathan
  page-navigation: true
  repo-url: https://github.com/vallejosgroup/lcmm-site
  repo-actions: [issue]

bibliography: references.bib
google-scholar: true
date: "last-modified"
title-block-banner: false

execute:
  freeze: auto
  cache: false

affiliations:
  - id: HGU
    name: "MRC Human Genetics Unit"
    city: "Edinburgh"
    region: "Scotland"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/mrc-human-genetics-unit"
  - id: CGEM
    name: "Centre for Genomic and Experimental Medicine"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://www.ed.ac.uk/centre-genomic-medicine"
  - id: IBD
    name: "Edinburgh IBD Unit"
    city: "Edinburgh"
    country: "United Kingdom"
    url: "https://services.nhslothian.scot/EdinburghIBDUnit/Pages/default.aspx"
  - id: Turing
    name: "The Alan Turing Institute"
    city: "London"
    country: "United Kingdom"
    url: "https://www.turing.ac.uk"


